### ISSUE TITLE
Generator for app / library does not obey --dry-run

### ISSUE THREAD

**Issue by AgentEnder** [AgentEnder/nx-dotnet#11]

**Comment by Jordan-Hall** [comment]
I'll have a fix for this when I finish the builder. It shouldn't be too difficult

**Comment by AgentEnder** [comment]
I think I can fix it pretty easily too, dotnet supports the -dry-run flag natively, just need to pass it in whenever the generator is ran in dry run mode

**Comment by AgentEnder** [comment]
Not quite fixed.
